name: JGB!&nbsp;Neat&nbsp;Design
email: jgbneatdesign@gmail.com
description: Web and Mobile Development Services from Jean Gérard Bousiquot.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jgbneatdesign.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook: jeangerarddev
twitter: jgb_solutions
instagram: jeangerarddev
github:  jgb-solutions
linkedin: jean-gérard-bousiquot-85a83689
google: +JeanGerardBousiquot_ND
owner: Jean Gérard Bousiquot

# Build settings
# markdown: kramdown
# gems:
#   - jekyll-feed
exclude: [
  "assets/source",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "gulpfile.js",
  "package.json",
  "package-lock.json",
  "yarn-error.log",
  "yarn.lock",
  "README.md"
]
