name: JGB!&nbsp;Neat&nbsp;Design
email: jgbneatdesign@gmail.com
description: Web and Mobile Development Services
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: jgbneatdesign
github:  jgbneatdesign
owner: Jean Gérard Bousiquot

# Build settings
markdown: kramdown
# theme: ""
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - assets/source
  - node_modules